/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaUsuario;

import CapaLogica.Arreglo;
import java.util.Arrays;

/**
 *
 * @author edgar
 */
public class VentanaMain extends javax.swing.JFrame {
//ENCAPSULAMIENTO

    private Arreglo generaArreglo = new Arreglo();
    private int opArreglo;
    private double[] copiaVector;
    private double tiempoTotal = 0;

    //Metodo que imprime copia ORDENAEDA del vector 
    private String imprimeOrdenado(double vect[]) {
        StringBuilder values = new StringBuilder();

        if (vect != null) {
            for (double value : vect) {
                values.append(value).append(" | ");
            }
        }
        return values.toString();
    }

    /**
     * Creates new form VentanaMain
     */
    public VentanaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOriginal = new javax.swing.JTextArea();
        botonGeneraArreglo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonBurbuja = new javax.swing.JButton();
        botonShell = new javax.swing.JButton();
        botonQuick = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombreAlgoritmo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOrdenado = new javax.swing.JTextArea();
        labelnano = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        botonConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EdgarJacobProyecto1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ARREGLO A ORDENAR"));

        txtOriginal.setEditable(false);
        txtOriginal.setColumns(20);
        txtOriginal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtOriginal.setRows(5);
        jScrollPane1.setViewportView(txtOriginal);

        botonGeneraArreglo.setText("GENERAR ARREGLO");
        botonGeneraArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneraArregloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(botonGeneraArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonGeneraArreglo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 430, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "HERRAMIENTAS DE ORDENACIÓN"));

        botonBurbuja.setBackground(new java.awt.Color(0, 102, 102));
        botonBurbuja.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonBurbuja.setText("ALGORITMO BURBUJA");
        botonBurbuja.setEnabled(false);
        botonBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBurbujaActionPerformed(evt);
            }
        });

        botonShell.setBackground(new java.awt.Color(102, 0, 0));
        botonShell.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonShell.setText("ALGORITMO SHELLSORT");
        botonShell.setEnabled(false);
        botonShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonShellActionPerformed(evt);
            }
        });

        botonQuick.setBackground(new java.awt.Color(204, 153, 0));
        botonQuick.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonQuick.setText("ALGORITMO QUICKSORT");
        botonQuick.setEnabled(false);
        botonQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBurbuja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonShell, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(botonQuick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBurbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonQuick)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 430, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("RESULTADOS"));

        jLabel3.setText("ALGORITMO UTILIZADO : ");

        jLabel5.setText("TIEMPO DE EJECUCIÖN :");

        jLabel7.setText("ARREGLO RESULTANTE  ");

        txtOrdenado.setColumns(20);
        txtOrdenado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtOrdenado.setRows(5);
        jScrollPane2.setViewportView(txtOrdenado);

        labelnano.setVisible(false);
        labelnano.setText("Nanosegundos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nombreAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 66, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelnano))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreAlgoritmo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tiempo)
                    .addComponent(labelnano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 430, 180));

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 70, 20));

        botonConfirmar.setBackground(new java.awt.Color(51, 255, 102));
        botonConfirmar.setForeground(new java.awt.Color(0, 51, 102));
        botonConfirmar.setText(">>>>>>>>>>>>>>>>>> CONFIRMAR <<<<<<<<<<<<<<<<<<<");
        botonConfirmar.setEnabled(false);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 430, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaUsuario/Appsortingfondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBurbujaActionPerformed
        try {
            copiaVector = Arrays.copyOf(generaArreglo.getArreglo(), 1000);
            
            //UNA VEZ ALMACENADO SE PROCEDE A ORDENARLO
            long inicio = System.nanoTime();
            generaArreglo.bubbleSort(copiaVector);
            long fin = System.nanoTime();

            tiempoTotal = (fin - inicio);
        } catch (Exception e) {

        }
        botonConfirmar.setEnabled(true);

        opArreglo = 1;
    }//GEN-LAST:event_botonBurbujaActionPerformed

    private void botonGeneraArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneraArregloActionPerformed

        try {
            generaArreglo.generaArreglo();

        } catch (Exception e) {

        }
        txtOriginal.setText(generaArreglo.getVectorValues());
        botonBurbuja.setEnabled(true);
        botonQuick.setEnabled(true);
        botonShell.setEnabled(true);
        labelnano.setVisible(false);


    }//GEN-LAST:event_botonGeneraArregloActionPerformed

    private void botonShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonShellActionPerformed
        try {
            //SE UTILIZA EL METODO ARRAYS COPY OF SOLO PARA GUARDAR LOS VALORES DEL ARREGLO ORIGINAL NO PARA ORDENARLO
            copiaVector = Arrays.copyOf(generaArreglo.getArreglo(), 1000);

            //UNA VEZ ALMACENADO SE PROCEDE A ORDENARLO
            long inicio = System.nanoTime();
            generaArreglo.shellSort(copiaVector);
            long fin = System.nanoTime();

            tiempoTotal = (fin - inicio);

        } catch (Exception e) {

        }
        //tiempoTotal = tiempoTotal/100; //TIEMPO PROMEDIADO EN MILLISEGUNDOS
        botonConfirmar.setEnabled(true);
        opArreglo = 2;// TODO add your handling code here:
    }//GEN-LAST:event_botonShellActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        txtOrdenado.setText(imprimeOrdenado(copiaVector));
        labelnano.setVisible(true);
        switch (opArreglo) {
            case 1:
                nombreAlgoritmo.setText("Burbuja");
                tiempo.setText(String.valueOf(tiempoTotal));
                break;
            case 2:
                nombreAlgoritmo.setText("ShellSort");
                tiempo.setText(String.valueOf(tiempoTotal));
                break;
            case 3:
                nombreAlgoritmo.setText("QuickSort");
                tiempo.setText(String.valueOf(tiempoTotal));
                break;

        }
        botonConfirmar.setEnabled(false);


    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void botonQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuickActionPerformed
        try {
            copiaVector = Arrays.copyOf(generaArreglo.getArreglo(), 1000);
            
            //UNA VEZ ALMACENADO SE PROCEDE A ORDENARLO
            long inicio = System.nanoTime();
           generaArreglo.quickSort(copiaVector, 0, copiaVector.length - 1);
            long fin = System.nanoTime();

            tiempoTotal = (fin - inicio);
        } catch (Exception e) {

        }
        botonConfirmar.setEnabled(true);
        opArreglo = 3;
    }//GEN-LAST:event_botonQuickActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new VentanaMain().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBurbuja;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonGeneraArreglo;
    private javax.swing.JButton botonQuick;
    private javax.swing.JButton botonShell;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel labelnano;
    private javax.swing.JLabel nombreAlgoritmo;
    private javax.swing.JLabel tiempo;
    private javax.swing.JTextArea txtOrdenado;
    private javax.swing.JTextArea txtOriginal;
    // End of variables declaration//GEN-END:variables
}
